using global::System.Text.Json;
using global::System.Text.Json.Serialization;
using RulebricksApi.Core;

namespace RulebricksApi;

[Serializable]
public record DeleteObjectResponseValues : IJsonOnDeserialized
{
    [JsonExtensionData]
    private readonly IDictionary<string, JsonElement> _extensionData =
        new Dictionary<string, JsonElement>();

    /// <summary>
    /// Values generated by the deleted object.
    /// </summary>
    [JsonPropertyName("total")]
    public int? Total { get; set; }

    /// <summary>
    /// Unused generated values that were permanently deleted.
    /// </summary>
    [JsonPropertyName("deleted")]
    public int? Deleted { get; set; }

    /// <summary>
    /// Retained generated values that lost their management lock.
    /// </summary>
    [JsonPropertyName("detached")]
    public int? Detached { get; set; }

    /// <summary>
    /// Referenced or explicitly retained generated values that were archived.
    /// </summary>
    [JsonPropertyName("archived")]
    public int? Archived { get; set; }

    [JsonIgnore]
    public ReadOnlyAdditionalProperties AdditionalProperties { get; private set; } = new();

    void IJsonOnDeserialized.OnDeserialized() =>
        AdditionalProperties.CopyFromExtensionData(_extensionData);

    /// <inheritdoc />
    public override string ToString()
    {
        return JsonUtils.Serialize(this);
    }
}
